server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    use-relative-redirects: true
  servlet:
    contextPath: '/api'


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ccpa7stkruda3o.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/d417m90et5hua3
    username: u3t363n286dfau
    password: pf42f4eb27acccf8a1b23cf13e6eeb3136cad8f7df6349d385acda3f93a835f67
  thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update




logging:
  level:
    org:
      apache:
        coyote:
          http11:
            Http11Processor: DEBUG
