server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    use-relative-redirects: true
  servlet:
    contextPath: '/api'


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/mbti_test?characterEncoding=UTF-8&serverTimezone=UTC
    #username: songheesu
    url: jdbc:postgresql://svc.sel4.cloudtype.app:30605/mbti_test
    username: root
    password: 10040160
  thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update




logging:
  level:
    org:
      apache:
        coyote:
          http11:
            Http11Processor: DEBUG
